### ISSUE TITLE
Publish flow: add diff visualization

### ISSUE THREAD

**Issue by jeremydw** [blinkk/rootjs#317]
## Context 

Edits to currently-live pages may be made by multiple people or over a long period of time. When pressing "publish", there is no easy way to visualize the diff of changes that are going live (without manually checking the preview pages). We need a way to visualize the changes (i.e. with a diff tool) so that the publisher can see exactly what changes will be published.

Note that there are a few other updates we can make to publishing, including adding checks and approver roles, but this issue is focused solely on providing the current user with a diff of the changes.

## Possible solution

Add a new "Show changes" accordion to the "Publish" modal that, when clicked, will show a JSON diff (or similar) of the changes.

## Example

Here's a rough mock of what this could look like. By the way, this only shows text changes. I think it'd be good to do this first, and then we can do a follow-up (i.e. with a tab) that can show a list of assets that are being published too (with previews), providing a quick visualization of new assets that are going live.

Note the diff viewer I pulled for the mock is https://github.com/aeolun/react-diff-viewer-continued

![image](https://github.com/blinkk/rootjs/assets/646525/28916dfd-b1d7-4eac-901e-a286e4fdd642)

**Comment by stevenle** [comment]
Starting to look into implementation now. Some notes:

* The diff viewer would be useful for showing changes between different versions in the version history as well, so the component should be generic enough to accept two doc ids and the versions of the docs to compare (e.g. version id or "draft" or "published").
* The renderer for the diff viewer should have some intelligent JSON diff'ing strategy (so ideally a library that specifically targets JSON) since we don't really need to diff any other type of code. I'm looking at something like https://github.com/eggachecat/react-jycm-viewer/
* Showing a list of "asset changes" sounds good, I can make sure the UI has some dedicated space for future features like that.
* In addition to the inline diff view we may want to also have a dedicated route (e.g. `/cms/diff?doc1=Pages/foo@published&doc2=Pages/foo@draft`) for opening in new tab which would be helpful for sharing with approvers as well as generally better UX for big diffs

**Comment by jeremydw** [comment]
Awesome. Oh, and it just occurred to me, this might be useful to have on releases too (similar to GitHub PRs). So if the component could be built in a way where it could be used on the Releases page, I think that'd be ideal.
